INSERT INTO `template_not` (`id_not`, `texto`) VALUES
(1, 'REQUISIÇÃO DE AMIZADE'),
(2, 'CONVITE CLA'),
(3, 'SOLICITA CLA'),
(4, 'CONQUISTA CLA1'),
(5, 'CONQUISTA CLA2'),
(6, 'CONQUISTA CLA3'),
(7, 'CONQUISTA CLA4'),
(8, 'CONQUISTA CLA5'),
(9, 'CONQUISTA CLA6'),
(10, 'CONQUISTA CLA7'),
(11, 'Seja bem vindo');
